### ISSUE TITLE
Fails when pam_lastlog is used

### ISSUE THREAD

**Issue by grodriguezl** [certtools/intelmq-api#33]
I'm running CentOS 7.

When lastlog is used in the PAM modules stack of sudo , it breaks all the data retrieved as it adds a string like ` Last login: Fri Feb 7 17:21:07 -03 2020` at the end every time `sudo` is used

Examples:
Management tab:
```
5:26 PM Error error botnet: {"cymru-whois-expert": "stopped",..., "url2fqdn-expert": "stopped"} Last Login: Fri Feb 7 17:26:44 -03 2020 SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data
```
Check tab:
![Screenshot from 2020-02-07 17-21-52](https://user-images.githubusercontent.com/13893086/74063046-697b4b80-49ce-11ea-8830-1caec739b3b8.png)

Of course I can remove lastlog module but maybe this error can be fixed easily

**Comment by ghost** [comment]
Does this also apply to the new Python-based backend?

**Comment by grodriguezl** [comment]
Hi, I switched jobs so I'm not working with intelmq any more :(

**Comment by ghost** [comment]
Ok. I'm closing here then. If the issue appears again for someone else, we can re-open.
